
export const ADD_VENTURE = 'ADD_VENTURE'
export const FETCH_VENTURE = 'FETCH_VENTURE'
export const FETCH_VENTUREs = 'FETCH_VENTUREs'
export const REMOVE_VENTURE = 'REMOVE_VENTURE'
export const UPDATE_VENTURE = 'UPDATE_VENTURE'

export const ADD_INVESTOR = 'ADD_INVESTOR'
export const FETCH_INVESTOR = 'FETCH_INVESTOR'
export const FETCH_INVESTORS = 'FETCH_INVESTORS'
export const REMOVE_INVESTOR = 'REMOVE_INVESTOR'
export const UPDATE_INVESTOR = 'UPDATE_INVESTOR'

export const ADD_MENTOR = 'ADD_MENTOR'
export const FETCH_MENTOR = 'FETCH_MENTOR'
export const FETCH_MENTORS = 'FETCH_MENTORS'
export const REMOVE_MENTOR = 'REMOVE_MENTOR'
export const UPDATE_MENTOR = 'UPDATE_MENTOR'

export const ADD_CAMPAIGN = 'ADD_CAMPAIGN'
export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN'
export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS'
export const REMOVE_CAMPAIGN = 'REMOVE_CAMPAIGN'
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN'

export const RESET_FORMS = 'RESET_FORMS'
export const UPDATE_FORMS_ASPECT = 'UPDATE_FORMS_ASPECT'
export const UPDATE_FORMS_REDUCER = 'UPDATE_FORMS_REDUCER'

export const RESET_APP = 'RESET_APP'
export const UPDATE_APP_ASPECT = 'UPDATE_APP_ASPECT'
export const UPDATE_APP_REDUCER = 'UPDATE_APP_REDUCER'

export const AUTH_SAGA = 'AUTH_SAGA'



